---
spring:
  config.activate.on-profile: dev 

inventory:
  property: "from dev"

aws.property: ${aws.secret}
---
spring:
  config.activate.on-profile: uat 

inventory:
  property: "from uat"


aws.property: ${aws.secret}
