---
spring:
  config.activate.on-profile: dev 

inventory:
  property: "dev-changed-1234"

aws:
  secret: ${mia-jv-aurora-postgres-dev-a89f58}
---
spring:
  config.activate.on-profile: uat 

inventory:
  property: "from uat"

aws:
  secret: ${mia-jv-aurora-postgres-dev-a89f58}
